bet/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'bet.views.index', name='index'),
    url(r'^make_bet$', 'bet.views.make_bet', name='make_bet'),
    url(r'^archive$', 'bet.views.archive', name='archive'),
    url(r'^best_betters$', 'bet.views.best_betters', name='best_betters'),
    url(r'^tour_result/more_info/(?P<betid>\d+)$', 'bet.views.more_info', name='more_info'),
    url(r'^tour_result/(?P<tourid>\d+)$', 'bet.views.tour_result', name='tour_result'),
    url(r'^check/(?P<tourid>\d+)$', 'bet.views.check', name='check'),
    url(r'^team$', 'bet.views.team', name='team'),
    url(r'^how_it_works$', 'bet.views.how_it_works', name='how_it_works'),

)

main/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),    reset_password_complate
    # url(r'^blog/', include('blog.urls')),     

    url(r'^$', 'main.views.main', name='main'),
    url(r'^signin/(?P<key>.+)$', 'main.views.signin', name='signin'),
    url(r'^signin$', 'main.views.signin', name='signin'),
    url(r'^signup$', 'main.views.signup', name='signup'),
    url(r'^signout$', 'main.views.signout', name='signout'),
    url(r'^team$', 'main.views.team', name='team'),
    url(r'^profile/modify_profile/$', 'main.views.modify_profile', name='modify_profile'),
    url(r'^profile/change_password/$', 'main.views.change_password', name='change_password'),
    url(r'^profile/$', 'main.views.profile', name='profile'),
)

reservation/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'reservation.views.index', name='index'), 
    url(r'^schedule/(?P<field_id>\d+)$', 'reservation.views.schedule', name='schedule'),
    url(r'^reserve/(?P<field_id>\d+)/(?P<day_id>\d+)$', 'reservation.views.reserve', name='reserve'),
    url(r'^list$', 'reservation.views.list', name='list'),
    url(r'^team$', 'reservation.views.team', name='team'),
)

www221kg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'www221kg.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^special/', include(admin.site.urls)),
    url(r'^reservation/',include('reservation.urls',namespace='reservation')),
    url(r'^news/',include('news.urls',namespace='news')),
    url(r'^bet/',include('bet.urls', namespace='bet')),
    url(r'^pro/',include('pro_owner.urls', namespace='pro_owner')),
	url(r'^',include('main.urls',namespace='main')),
    url(r'^',include('password_reset.urls')),
    
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)
urlpatterns += patterns('',
   (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.MEDIA_ROOT}))

reservation/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class Field(models.Model):
    image1 = models.ImageField('фото1', upload_to='media')
    image2 = models.ImageField('фото2', upload_to='media')
    image3 = models.ImageField('фото3', upload_to='media')
    image4 = models.ImageField('фото4', upload_to='media', null=True, blank=True)
    image5 = models.ImageField('фото5', upload_to='media', null=True, blank=True)
    map_image = models.ImageField('карта', upload_to='media')
    owner = models.ForeignKey(User, verbose_name='владелец')
    name = models.CharField('название', max_length=200)
    width = models.IntegerField('ширина')
    height = models.IntegerField('длина')
    price_usual = models.IntegerField('цена вечером')
    price_low = models.IntegerField('цена днем')
    address = models.CharField('адрес', max_length=250)
    shower = models.BooleanField('душ', default=False)
    changing_room = models.BooleanField('раздевалка', default=False)
    wc = models.BooleanField('туалет', default=False)
    note1 = models.TextField('примечания1', blank=True, null=True)
    note2 = models.TextField('координаты_x', blank=True, null=True)
    note3 = models.TextField('координаты_y', blank=True, null=True)

    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = 'поле'
        verbose_name_plural = 'поля'

class Day(models.Model):
    h9_00 = models.BooleanField('09:00-09:30', default=False)
    h9_30 = models.BooleanField('09:30-10:00', default=False)
    h10_00 = models.BooleanField('10:00-10:30', default=False)
    h10_30 = models.BooleanField('10:30-11:00', default=False)
    h11_00 = models.BooleanField('11:00-11:30', default=False)
    h11_30 = models.BooleanField('11:30-12:00', default=False)
    h12_00 = models.BooleanField('12:00-12:30', default=False)
    h12_30 = models.BooleanField('12:30-13:00', default=False)
    h13_00 = models.BooleanField('13:00-13:30', default=False)
    h13_30 = models.BooleanField('13:30-14:00', default=False)
    h14_00 = models.BooleanField('14:00-14:30', default=False)
    h14_30 = models.BooleanField('14:30-15:00', default=False)
    h15_00 = models.BooleanField('15:00-15:30', default=False)
    h15_30 = models.BooleanField('15:30-16:00', default=False)
    h16_00 = models.BooleanField('16:00-16:30', default=False)
    h16_30 = models.BooleanField('16:30-17:00', default=False)
    h17_00 = models.BooleanField('17:00-17:30', default=False)
    h17_30 = models.BooleanField('17:30-18:00', default=False)
    h18_00 = models.BooleanField('18:00-18:30', default=False)
    h18_30 = models.BooleanField('18:30-19:00', default=False)
    h19_00 = models.BooleanField('19:00-19:30', default=False)
    h19_30 = models.BooleanField('19:30-20:00', default=False)
    h20_00 = models.BooleanField('20:00-20:30', default=False)
    h20_30 = models.BooleanField('20:30-21:00', default=False)
    h21_00 = models.BooleanField('21:00-21:30', default=False)
    h21_30 = models.BooleanField('21:30-22:00', default=False)
    h22_00 = models.BooleanField('22:00-22:30', default=False)
    h22_30 = models.BooleanField('22:30-23:00', default=False)
    h23_00 = models.BooleanField('23:00-23:30', default=False)
    h23_30 = models.BooleanField('23:30-00:00', default=False)
    h24_00 = models.BooleanField('00:00-00:30', default=False)
    h24_30 = models.BooleanField('00:30-01:00', default=False)

    weather = models.TextField('погода', default='здесь должна быть информация о погоде')
    field = models.ForeignKey(Field, verbose_name='поле')
    day_of_week = models.CharField('день недели', max_length = 50)
    date = models.DateField('дата')
    
    def __unicode__(self):
        return self.day_of_week +" of "+ str(self.field)

    class Meta:
        verbose_name = 'день'
        verbose_name_plural = 'дни'
    
class BookRequest(models.Model):
    user = models.ForeignKey(User, verbose_name='пользователь')
    time = models.CharField('забранированное время', max_length = 250)
    date_time = models.DateField('дата')
    field = models.ForeignKey(Field, verbose_name='поле')
    time_booked = models.DateTimeField('дата заявки', default=datetime.now)
    
    def __unicode__(self):
        return self.user.username + ' ' + str(self.field.name) + ' ' + str(self.date_time)

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'

reservation/views.py
#imports form django libraries
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse ,reverse_lazy
from django.template import RequestContext
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
#imports from models
from .models import Day, Field,BookRequest
#imports from 3-rd party libraries
import requests

# Create your views here.
def index(request):
	"""returns reservation manin page"""

	return render_to_response('reservation/index.html', {}, context_instance = RequestContext(request))

def team(request):
	"""returns rendered our team page"""

	return render_to_response('reservation/team.html', {}, context_instance = RequestContext(request))

def schedule(request,field_id = 1):
	"""shows the schedule for particular field"""
	#define variables
	args = {}
	hours = []
	#getting data form models
	field = get_object_or_404(Field, pk = field_id)
	days = field.day_set.all() 
	
	#gettin hours to show
	for i in range(9,24):
		hours += [i]	
	#context data initialization into dictionary 'args'
	args['field'] = field
	args['hours'] = hours
	args['days'] = days

	return render_to_response('reservation/schedule.html',args,context_instance = RequestContext(request))

def list(request):
	"""this view shows the list of all fields as a list"""
	#define variables
	args = {}
	#gettin hours to show
	fields = Field.objects.all()
	#context data initialization into dictionary 'args'
	args['fields'] = fields

	return render_to_response('reservation/list.html',args,context_instance = RequestContext(request))

def reserve(request,field_id,day_id):
	"""this view is manipulates fields hours"""
	#define variables
	args={}
	args.update(csrf(request))
	message = "Chislo : "
	hours1 = []
	hours2 = []

	for i in range(9,17):
		hours1 += [i]
	for i in range(17,25):
		hours2 += [i]

	if request.POST:
		#gettin hours to show
		user = request.user
		date_time = get_object_or_404(Day, pk = day_id).date
		field = get_object_or_404(Field, pk = field_id)
		allhours = request.POST.getlist('hour')
		begin_time = ''
		
		for hour in allhours:
			begin_time = begin_time + (hour + ', ')


		valid = True
		if len(allhours) < 2:
			valid = False
			hour_error = "Выберите время не менее одного часа"
			args['hour_error'] = hour_error

		if valid ==  False:
			#context data initialization into dictionary 'args'
			args['field'] = get_object_or_404(Field, pk = field_id)
			args['hours1'] = hours1
			args['hours2'] = hours2
			args['day'] = get_object_or_404(Day, pk = day_id)

			return render_to_response('reservation/reserve.html',args,context_instance = RequestContext(request))

		bookRequest = BookRequest.objects.create(user=user,time = allhours,date_time=date_time,field=field)
		bookRequest.full_clean()
		
		day = get_object_or_404(Day, pk = day_id)
		
		for hour in allhours:
			
			if hour == '09-00':
				day.h9_00 = True
			if hour == '09-30':
				day.h9_30 = True
			if hour == '10-00':
				day.h10_00 = True
			if hour == '10-30':
				day.h10_30 = True
			if hour == '11-00':
				day.h11_00 = True
			if hour == '11-30':
				day.h11_30 = True
			if hour == '12-00':
				day.h12_00 = True
			if hour == '12-30':
				day.h12_30 = True
			if hour == '13-00':
				day.h13_00 = True
			if hour == '13-30':
				day.h13_30 = True
			if hour == '14-00':
				day.h14_00 = True
			if hour == '14-30':
				day.h14_30 = True
			if hour == '15-00':
				day.h15_00 = True
			if hour == '15-30':
				day.h15_30 = True
			if hour == '16-00':
				day.h16_00 = True
			if hour == '16-30':
				day.h16_30 = True
			if hour == '17-00':
				day.h17_00 = True
			if hour == '17-30':
				day.h17_30 = True
			if hour == '18-00':
				day.h18_00 = True
			if hour == '18-30':
				day.h18_30 = True
			if hour == '19-00':
				day.h19_00 = True
			if hour == '19-30':
				day.h19_30 = True
			if hour == '20-00':
				day.h20_00 = True
			if hour == '20-30':
				day.h20_30 = True
			if hour == '21-00':
				day.h21_00 = True
			if hour == '21-30':
				day.h21_30 = True
			if hour == '22-00':
				day.h22_00 = True
			if hour == '22-30':
				day.h22_30 = True
			if hour == '23-00':
				day.h23_00 = True
			if hour == '23-30':
				day.h23_30 = True
			if hour == '24-00':
				day.h24_00 = True
			if hour == '24-30':
				day.h24_30 = True
		
		day.full_clean()
		
		message +=  str(day.date) + "\nzabranirovano : "

		message += ', '.join(allhours)

		sms_url = 'http://smsc.ru/sys/send.php?login=traktorist221&psw=smsc120701&phones=996556606737&mes='
		message += '\nfrom 221.kg'
		sms_url += message
		#send sms by httpget
		r = requests.get(sms_url)
		

		#save inctances to the db
		day.save()
		bookRequest.save()
		field = get_object_or_404(Field, pk = field_id)
		#send_mail(subject,message,from_email,to_list,fail_silently=False)
		message_body = 'Вы забронировали ' + field.name + ' \n дата: ' + str(day.date) + '\n время: (' + ', '.join(allhours) + ')' + '\n + желаем вам приятной игры'
		send_mail('Бронирование 221', message_body, settings.EMAIL_HOST_USER, [user.email], fail_silently = True)
		#context data initialization into dictionary 'args'
		args['field'] = field
		args['hours1'] = hours1
		args['hours2'] = hours2
		args['day'] = get_object_or_404(Day, pk = day_id)
		args['success_message'] = "вы успешно забронировали поле (" + ', '.join(allhours) + ")"

		return render_to_response('reservation/reserve.html',args,context_instance = RequestContext(request))

	else:
		#context data initialization into dictionary 'args'
		args['field'] = get_object_or_404(Field,pk = field_id)
		args['hours1'] = hours1
		args['hours2'] = hours2
		args['day'] = get_object_or_404(Day, pk = day_id)

		return render_to_response('reservation/reserve.html',args,context_instance = RequestContext(request))

reservation/templates/reservation/list.html
{% load staticfiles %}
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>221.kg</title>

    <!-- here is the font which we have got from google -->
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <!-- Bootstrap core CSS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/reservation-css.css' %}" rel="stylesheet">
    
    <!-- here we have font-awsome link -->
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css'%}">
  </head>

  <body>
   <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVJK9M"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MVJK9M');</script>
  <!-- End Google Tag Manager -->

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" href="{% url 'reservation:index'%}"> <img id="logo" src="{% static 'images/logo1.png'%}"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href={% url 'reservation:list'%}>Забронировать поле</a></li>
            <li><a href="#contact">Как это работает</a></li>
            <li><a href="{% url 'reservation:team'%}">О нас</a></li>
            <li><a href="#footer">Kонтакты</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'main:profile' %}">{{user.username}}</a></li>
            <li>
            <a><span data-toggle="modal" data-target="#signout"><span style="cursor:pointer">выйти</span></span></a>
            </li>
            {% else %}
            <li><a href="{% url 'main:signin' 'reservation' %}">Войти</a></li>
            <li><a href="{% url 'main:signup' %}">Регистрация</a></li>
            {% endif %}
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Here we have maincontent -->
    <div class="maincontent">
   
   <div class="list">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2 class="text-center">Искусственные поля и залы  для футбола Бишкека</h2>
                <br><br><br>
                <br><br>
                
                
                
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="{% static 'images/field_1.jpg'%}" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="{% static 'images/field_2.jpg'%}" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="{% static 'images/field_3.jpg'%}" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                {% for field in fields %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                            <a style = "decoration:none;" href="{% url 'reservation:schedule' field.id%}">
                            <div class="thumbnail">
                                
                                <img height="150" width="320" class="images" src="../../media/{{field.image1}}" alt='image1'>
                                <div class="caption">
                                    <h4 class="pull-right">{{field.price_low}} сом/час</h4>
                                    <h4 style="color:red">{{field.name}}</h4>
                                    <p>{{field.address}}</p>
                                </div>
                            </div>
                              
                            </a>
                            
                    </div>
                {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </div>

    </div><!-- maincontent -->
    
 <div class="footer">
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span>Подпишись на наш Twitter<br>
            </a>

            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
              </span>Cтраничка Facebook <br>
            </a>  
          </div>

          <div class="col-md-6">
            <span class="fa-stack fa-lg text-left">
               <i class="fa fa-square-o fa-stack-2x"></i>
               <i class="fa fa-phone fa-stack-1x"></i>
            </span> +996556606737<br>
            <span class="fa-stack fa-lg text-left">
              <i class="fa fa-square-o fa-stack-2x"></i>
              <i class="fa fa-map-marker fa-stack-1x"></i>
            </span>Тунгуч,улица Анкара 1/8<br>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- Core JavaScript Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> 
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    
    <!-- Exit  model page -->
    <div class="modal fade" id="signout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{user.first_name}} {{user.last_name}}</h4>
            </div>
            <div class="modal-body">
                <h4>вы уверены что хотите выйти?</h4>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <a href="{% url 'main:signout'%}"><button type="button" class="btn btn-primary">Выйти</button></a>
                </div>
            </div>
        </div>
      </div>
    </div>
    
<!-- WWW.NET.KG , code for http://221.kg -->
<script language="javascript" type="text/javascript">
 java="1.0";
 java1=""+"refer="+escape(document.referrer)+"&amp;page="+escape(window.location.href);
 document.cookie="astratop=1; path=/";
 java1+="&amp;c="+(document.cookie?"yes":"now");
</script>
<script language="javascript1.1" type="text/javascript">
 java="1.1";
 java1+="&amp;java="+(navigator.javaEnabled()?"yes":"now");
</script>
<script language="javascript1.2" type="text/javascript">
 java="1.2";
 java1+="&amp;razresh="+screen.width+'x'+screen.height+"&amp;cvet="+
 (((navigator.appName.substring(0,3)=="Mic"))?
 screen.colorDepth:screen.pixelDepth);
</script>
<script language="javascript1.3" type="text/javascript">java="1.3"</script>
<script language="javascript" type="text/javascript">
 java1+="&amp;jscript="+java+"&amp;rand="+Math.random();
 document.write("<a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'>"+
 "<img src='http://www.net.kg/img.php?id=4236&amp;"+java1+
 "' border='0' alt='WWW.NET.KG' width='88' height='10' /></a>");
</script>
<noscript>
 <a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'><img
  src="http://www.net.kg/img.php?id=4236" border='0' alt='WWW.NET.KG' width='88'
  height='10' /></a>
</noscript>
<!-- /WWW.NET.KG -->

 </body>
</html>
    
    