bet/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'bet.views.index', name='index'),
    url(r'^make_bet$', 'bet.views.make_bet', name='make_bet'),
    url(r'^archive$', 'bet.views.archive', name='archive'),
    url(r'^best_betters$', 'bet.views.best_betters', name='best_betters'),
    url(r'^tour_result/more_info/(?P<betid>\d+)$', 'bet.views.more_info', name='more_info'),
    url(r'^tour_result/(?P<tourid>\d+)$', 'bet.views.tour_result', name='tour_result'),
    url(r'^check/(?P<tourid>\d+)$', 'bet.views.check', name='check'),
    url(r'^team$', 'bet.views.team', name='team'),
    url(r'^how_it_works$', 'bet.views.how_it_works', name='how_it_works'),

)

news/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'appname.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'news.views.index', name='index'),
    url(r'^team/(?P<league_id>\d+)/(?P<team_id>\d+)$', 'news.views.team', name='team'),
    url(r'^league/(?P<league_id>\d+)$', 'news.views.league', name='league'),
    url(r'^news/(?P<news_id>\d+)$', 'news.views.news', name='news'),
)

www221kg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'www221kg.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^special/', include(admin.site.urls)),
    url(r'^reservation/',include('reservation.urls',namespace='reservation')),
    url(r'^news/',include('news.urls',namespace='news')),
    url(r'^bet/',include('bet.urls', namespace='bet')),
    url(r'^pro/',include('pro_owner.urls', namespace='pro_owner')),
	url(r'^',include('main.urls',namespace='main')),
    url(r'^',include('password_reset.urls')),
    
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)
urlpatterns += patterns('',
   (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.MEDIA_ROOT}))

news/models.py
from django.db import models
from datetime import datetime 
from django.contrib.auth.models import User

# Create your models here.
class League(models.Model):
	"""League class is the class which represents football Leagues"""
	name = models.CharField('название', max_length = 100)
	slogan = models.CharField('девиз', max_length = 300)
	image1 = models.ImageField('фото', upload_to = 'media/league')
	
	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = 'лига'
		verbose_name_plural = 'лиги'

class Team(models.Model):
	"""Team class is the class which represents football Team"""
	name = models.CharField('название', max_length = 100)
	slogan = models.CharField('девиз', max_length = 300)
	league = models.ForeignKey(League, verbose_name='лига')
	image1 = models.ImageField('фото', upload_to = 'media/team')

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = 'команда'
		verbose_name_plural = 'команды'

class News(models.Model):
	"""News class is the class which represents news for particular Team"""
	image = models.ImageField('фото', upload_to = 'media/news',null=True, blank=True)
	date = models.DateTimeField('дата' ,default=datetime.now)
	team = models.ForeignKey(Team, verbose_name='команда')
	title = models.CharField('тема', max_length = 200, null=True, blank=True)
	description = models.TextField('короткое изложение', null=True, blank=True)
	body = models.TextField('новость', null=True, blank=True)
	user = models.ForeignKey(User, verbose_name='ползователь')
	
	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name = 'новости'
		verbose_name_plural = 'новости'
	

news/views.py
#importing django libraries
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse ,reverse_lazy
#importing models
from news.models import League,Team,News
#importing form python libraries
from datetime import datetime 


def index(request):
	"""returns rendered main page of news app"""

	#define variables
	args = {}
	all_teams = []
	all_news = []
	
	#getting data form models
	leagues = League.objects.all()
	
	#in this loop we get all teams in our all leagues to a 'all_teams' list 
	for league in leagues:
		all_teams += league.team_set.all()

	#in this loop we get all new form every team which is in 'all_teams' list and place that new into 'all_news' list  
	for team in all_teams:
		all_news += team.news_set.all()

	#sort news by date so that last news pop up first
	all_news = reversed(sorted(all_news, key=lambda ne:ne.date))
	#taking forst 50 news of all news
	all_news = list(all_news)[:50]
	#context data initialization into dictionary 'args'
	args['news'] = all_news
	args['leagues'] = leagues

	return render_to_response('news/index.html',args)

def league(request,league_id=1):
	"""return rendered news page for particular league"""

	#define variables
	args = {}
	news = []

	#getting data form models
	this_league = get_object_or_404(League, pk = league_id)
	leagues = League.objects.all().exclude(pk = league_id).order_by('name')
	teams = this_league.team_set.all().order_by('name')
	
	#collecting all news of leagu into 'news' list
	for team in teams:
		news += team.news_set.all()

	#sort news by date so that last news pop up first
	news = reversed(sorted(news, key=lambda ne:ne.date))
	#taking forst 40 news of all news
	news = list(news)[:40]
	#context data initialization into dictionary 'args'
	args['teams'] = teams
	args['this_league'] = this_league
	args['leagues'] = leagues
	args['news'] = news

	return render_to_response('news/league.html',args)
	
def team(request,league_id = 1,team_id = -1):
	"""return rendered news page for particular team"""

	#define variables
	args = {}

	#getting data form models
	this_team = get_object_or_404(Team, pk = team_id)
	news = this_team.news_set.all().order_by('date')
	this_league = get_object_or_404(League, pk = league_id)
	teams = this_league.team_set.all().exclude(pk = team_id).order_by('name')
	leagues = League.objects.all().exclude(pk = league_id).order_by('name')

	#context data initialization into dictionary 'args'
	args['this_team'] = this_team
	args['this_league'] = this_league
	args['teams'] = teams
	args['leagues'] = leagues
	args['news'] = news
	
	return render_to_response('news/team.html',args)

def news(request,news_id):
	""" returns particular rendered news """

	#define variables
	args = {}
	
	#getting data form models
	news = get_object_or_404(News, pk = news_id)
	leagues = League.objects.all().order_by('name')

	#context data initialization into dictionary 'args'
	args['news'] = news
	args['leagues'] = leagues

	return render_to_response('news/news.html',args)

news/templates/news/league.html
{% load staticfiles %}
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>221.kg</title>

    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/clean-news.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css'%}">
    
  </head>

  <body>
  <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVJK9M"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MVJK9M');</script>
  <!-- End Google Tag Manager -->
 
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" href="{% url 'news:index'%}"> <img id="logo" src="{% static 'images/logo1.png'%}"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'main:team'%}">О нас</a></li>
            <li><a href="#footer">Kонтакты</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <header class="intro-header" style="background-image: url(../../../media/{{this_league.image1}})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{this_league.name}}</h1>
                        <hr class="small">
                        <span class="subheading">{{this_league.slogan}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Here we have maincontent -->
    <br><br>
    <div class="container">
      <div class="row">
        <div class="col-md-3" style="">
          <a href="{% url 'news:index'%}"><h4>все новости</h4></a>
          <h4>Leagues</h4>
          <h5 style="color:green">{{this_league}}</h5>
          <ul>
            <li style="color:green"><h5>все новости</h5></li>
            {% for team in teams %}
              <li><h5><a href="{% url 'news:team' this_league.id team.id %}">{{team.name}}</a></h5></li>
            {% endfor %}
          </ul>
          {% for league in leagues %}
            <h5><a href="{% url 'news:league' league.id %}">{{league.name}}</a></h5>
          {% endfor %}
        </div>

        <div class="col-md-6">
          {% for new in news %}
          <div class="post-preview">
            <a href="{% url 'news:news' new.id %}">
              <h4 class="post-title">
                {{new.title}}
              </h4>
              <h5 class="post-subtitle">
                {{new.description}}
              </h5>
            </a>
            <p class="post-meta">   {{new.date}} {{new.user}} </p>
          </div>
          <hr>
          {% endfor %}  
        </div>
      </div>
    </div>
    <br><br>

    <!-- footer -->

  <div class="footer">
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span>Подпишись на наш Twitter<br>
            </a>

            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
              </span>Cтраничка Facebook <br>
            </a>  
          </div>

          <div class="col-md-6">
            <span class="fa-stack fa-lg text-left">
               <i class="fa fa-square-o fa-stack-2x"></i>
               <i class="fa fa-phone fa-stack-1x"></i>
            </span> +996556606737<br>
            <span class="fa-stack fa-lg text-left">
              <i class="fa fa-square-o fa-stack-2x"></i>
              <i class="fa fa-map-marker fa-stack-1x"></i>
            </span>Тунгуч,улица Анкара 1/8<br>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <!-- Core JavaScript Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> 
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>


<!-- WWW.NET.KG , code for http://221.kg -->
<script language="javascript" type="text/javascript">
 java="1.0";
 java1=""+"refer="+escape(document.referrer)+"&amp;page="+escape(window.location.href);
 document.cookie="astratop=1; path=/";
 java1+="&amp;c="+(document.cookie?"yes":"now");
</script>
<script language="javascript1.1" type="text/javascript">
 java="1.1";
 java1+="&amp;java="+(navigator.javaEnabled()?"yes":"now");
</script>
<script language="javascript1.2" type="text/javascript">
 java="1.2";
 java1+="&amp;razresh="+screen.width+'x'+screen.height+"&amp;cvet="+
 (((navigator.appName.substring(0,3)=="Mic"))?
 screen.colorDepth:screen.pixelDepth);
</script>
<script language="javascript1.3" type="text/javascript">java="1.3"</script>
<script language="javascript" type="text/javascript">
 java1+="&amp;jscript="+java+"&amp;rand="+Math.random();
 document.write("<a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'>"+
 "<img src='http://www.net.kg/img.php?id=4236&amp;"+java1+
 "' border='0' alt='WWW.NET.KG' width='88' height='10' /></a>");
</script>
<noscript>
 <a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'><img
  src="http://www.net.kg/img.php?id=4236" border='0' alt='WWW.NET.KG' width='88'
  height='10' /></a>
</noscript>
<!-- /WWW.NET.KG -->

  </body>
</html>
    
    

news/templates/news/team.html
{% load staticfiles %}
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>221.kg</title>

    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/clean-news.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css'%}">
    
  </head>

  <body>

  <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVJK9M"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MVJK9M');</script>
  <!-- End Google Tag Manager -->

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" href="{% url 'news:index'%}"> <img id="logo" src="{% static 'images/logo1.png'%}"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'main:team'%}">О нас</a></li>
            <li><a href="#footer">Kонтакты</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    <header class="intro-header" style="background-image: url(../../../media/{{this_team.image1}})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{this_team.name}}</h1>
                        <hr class="small">
                        <span class="subheading">{{this_team.slogan}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Here we have maincontent -->
    <br><br>


    <div class="container">

      <div class="row">
        <div class="col-md-3">
          <a href="{% url 'news:index'%}"><h4>все новости</h4></a>
          <h4>Leagues</h4>
          <h5 style="color:green">{{this_league.name}}</h5>
          <ul>
            <li><h5><a href="{% url 'news:league' this_league.id %}">все новости</a></h5></li>
            <li><h5 style="color:green">{{this_team.name}}</h5></li>
            {% for team in teams %}
              <li><h5><a href="{% url 'news:team' this_league.id team.id %}">{{team.name}}</a></h5></li>
            {% endfor %}
          </ul>
          {% for league in leagues %}
            <h5><a href="{% url 'news:league' league.id %}">{{league.name}}</a></h5>
          {% endfor %}
        </div>

        <div class="col-md-8">
          {% for new in news %}
          <div class="post-preview">
            <a href="{% url 'news:news' new.id %}">
              <h4 class="post-title">
                {{new.title}}
              </h4>
              <h5 class="post-subtitle">
                {{new.description}}
              </h5>
            </a>
               <p class="post-meta">   {{new.date}} {{new.user}} </p>
          </div>
          <hr>
          {% endfor %}
        </div>

      </div>

    </div>


    <br><br>

  <div class="footer">
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span>Подпишись на наш Twitter<br>
            </a>

            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
              </span>Cтраничка Facebook <br>
            </a>  
          </div>

          <div class="col-md-6">
            <span class="fa-stack fa-lg text-left">
               <i class="fa fa-square-o fa-stack-2x"></i>
               <i class="fa fa-phone fa-stack-1x"></i>
            </span> +996556606737<br>
            <span class="fa-stack fa-lg text-left">
              <i class="fa fa-square-o fa-stack-2x"></i>
              <i class="fa fa-map-marker fa-stack-1x"></i>
            </span>Тунгуч,улица Анкара 1/8<br>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- Core JavaScript Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> 
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>


<!-- WWW.NET.KG , code for http://221.kg -->
<script language="javascript" type="text/javascript">
 java="1.0";
 java1=""+"refer="+escape(document.referrer)+"&amp;page="+escape(window.location.href);
 document.cookie="astratop=1; path=/";
 java1+="&amp;c="+(document.cookie?"yes":"now");
</script>
<script language="javascript1.1" type="text/javascript">
 java="1.1";
 java1+="&amp;java="+(navigator.javaEnabled()?"yes":"now");
</script>
<script language="javascript1.2" type="text/javascript">
 java="1.2";
 java1+="&amp;razresh="+screen.width+'x'+screen.height+"&amp;cvet="+
 (((navigator.appName.substring(0,3)=="Mic"))?
 screen.colorDepth:screen.pixelDepth);
</script>
<script language="javascript1.3" type="text/javascript">java="1.3"</script>
<script language="javascript" type="text/javascript">
 java1+="&amp;jscript="+java+"&amp;rand="+Math.random();
 document.write("<a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'>"+
 "<img src='http://www.net.kg/img.php?id=4236&amp;"+java1+
 "' border='0' alt='WWW.NET.KG' width='88' height='10' /></a>");
</script>
<noscript>
 <a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'><img
  src="http://www.net.kg/img.php?id=4236" border='0' alt='WWW.NET.KG' width='88'
  height='10' /></a>
</noscript>
<!-- /WWW.NET.KG -->

 </body>
</html>
    
    