bet/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'bet.views.index', name='index'),
    url(r'^make_bet$', 'bet.views.make_bet', name='make_bet'),
    url(r'^archive$', 'bet.views.archive', name='archive'),
    url(r'^best_betters$', 'bet.views.best_betters', name='best_betters'),
    url(r'^tour_result/more_info/(?P<betid>\d+)$', 'bet.views.more_info', name='more_info'),
    url(r'^tour_result/(?P<tourid>\d+)$', 'bet.views.tour_result', name='tour_result'),
    url(r'^check/(?P<tourid>\d+)$', 'bet.views.check', name='check'),
    url(r'^team$', 'bet.views.team', name='team'),
    url(r'^how_it_works$', 'bet.views.how_it_works', name='how_it_works'),

)

main/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),    reset_password_complate
    # url(r'^blog/', include('blog.urls')),     

    url(r'^$', 'main.views.main', name='main'),
    url(r'^signin/(?P<key>.+)$', 'main.views.signin', name='signin'),
    url(r'^signin$', 'main.views.signin', name='signin'),
    url(r'^signup$', 'main.views.signup', name='signup'),
    url(r'^signout$', 'main.views.signout', name='signout'),
    url(r'^team$', 'main.views.team', name='team'),
    url(r'^profile/modify_profile/$', 'main.views.modify_profile', name='modify_profile'),
    url(r'^profile/change_password/$', 'main.views.change_password', name='change_password'),
    url(r'^profile/$', 'main.views.profile', name='profile'),
)

www221kg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'www221kg.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^special/', include(admin.site.urls)),
    url(r'^reservation/',include('reservation.urls',namespace='reservation')),
    url(r'^news/',include('news.urls',namespace='news')),
    url(r'^bet/',include('bet.urls', namespace='bet')),
    url(r'^pro/',include('pro_owner.urls', namespace='pro_owner')),
	url(r'^',include('main.urls',namespace='main')),
    url(r'^',include('password_reset.urls')),
    
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)
urlpatterns += patterns('',
   (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.MEDIA_ROOT}))

bet/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class Tour(models.Model):
    tour_number = models.IntegerField('номер тура', primary_key=True)
    tour_end = models.CharField('ставки берутся до', max_length=100)
    tour_prize = models.CharField('приз тура', max_length=50)
    tour_note1 = models.CharField('примечание1', max_length=100,blank=True,null=True)
    tour_note2 = models.CharField('примечание2', max_length=100,blank=True,null=True)
    tour_note3 = models.CharField('примечание3', max_length=100,blank=True,null=True)
    
    def __unicode__(self):
        return str(self.tour_number)

    class Meta:
        verbose_name = 'тур'
        verbose_name_plural = 'тура'

class Match(models.Model):
    tour = models.ForeignKey(Tour, verbose_name='тур')
    first_team = models.CharField('первая команда', max_length = 62)
    second_team = models.CharField('вторая команда', max_length = 62)
    goal_first = models.IntegerField('голы первой команды', default = 0)
    goal_second = models.IntegerField('голы второй команды', default = 0)
    def __unicode__(self):
        return self.first_team + " vs " + self.second_team

    class Meta:
        verbose_name = 'матч'
        verbose_name_plural = 'матчи'
    
class Bet(models.Model):
    user = models.ForeignKey(User, verbose_name='ползователь')
    tour_number = models.IntegerField('номер тура', default = 0)
    correct_num = models.IntegerField('правильные исходы', default = 0)
    date = models.DateTimeField('дата ставки', default=datetime.now)
    match1 = models.IntegerField('матч1')
    match2 = models.IntegerField('матч2')
    match3 = models.IntegerField('матч3')
    match4 = models.IntegerField('матч4')
    match5 = models.IntegerField('матч5')
    match6 = models.IntegerField('матч6')
    match7 = models.IntegerField('матч7')
    match8 = models.IntegerField('матч8')
    match9 = models.IntegerField('матч9')
    match10 = models.IntegerField('матч10')
    
    def __unicode__(self):
        return str(self.user) +" "+ str(self.tour_number)

    class Meta:
        verbose_name = 'ставка'
        verbose_name_plural = 'ставки'


class CurrentTour(models.Model):
    tour_number = models.IntegerField('номер тура', default = 1)
    
    def __unicode__(self):
        return str(self.tour_number)

    class Meta:
        verbose_name = 'номер тура этой недели'
        verbose_name_plural = 'номер тура этой недели'
        
        
        

bet/views.py
from __future__ import unicode_literals
# imports form djagno
from django.shortcuts import render, render_to_response,redirect,get_object_or_404
from django.core.urlresolvers import reverse ,reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
#imports form model
from .models import Match, Bet, Tour, CurrentTour
from django.contrib.auth.models import User


# Create your views here.
def index(request):
	"""returns main page of bet app"""

	return render_to_response('bet/index.html',{},context_instance = RequestContext(request))

def archive(request):
	#define variables
	args = {}

	#getting data form models
	tours = Tour.objects.all()
    #do not include last ona because it has not result yet
	tours = tours[:len(tours)-1]

    #context data initialization into dictionary 'args'
	args['tours'] = tours

	return render_to_response('bet/archive.html',args,context_instance = RequestContext(request))

def tour_result(request,tourid):
	"""return rende results page for particular tour"""
	#define variables
	args = {}

    #if user is authenticated it gives extra information	
	if request.user.is_authenticated():
		user_bet = Bet.objects.filter(tour_number = tourid,user = request.user)
		if user_bet.count() == 1:
			args['user_bet'] = user_bet[0]
	
	#getting data form models
	bets = Bet.objects.filter(tour_number = tourid)
    #sort results by ranking of true results
	bets_temp = sorted(bets, key=lambda x: x.correct_num , reverse=True)

    #paginate 25 news per one page
	paginator = Paginator(bets_temp, 25)
	page = request.GET.get('page')
    
	try:
		bets_partial = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		bets_partial = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		bets_partial = paginator.page(paginator.num_pages)
    
    #context data initialization into dictionary 'args'
	args["bets_partial"] = bets_partial
	args['tour'] = tourid

	return render_to_response('bet/tour_result.html',args,context_instance = RequestContext(request))

def best_betters(request):
	"""returns best betters list with statistics"""
	#define variables
	args = {}
	results = {}
	keys = []
	#getting data form models
	tour_current = CurrentTour.objects.all()[0]
	if request.user.is_authenticated():
		user_result = {}
		average = 0
		bets = request.user.bet_set.all().exclude(tour_number = tour_current.tour_number)
		if bets.count() > 0:
			for bet in bets:
				average += bet.correct_num
			average = average / (bets.count())
			user_result[request.user.username] = average
			args['user_result'] = user_result

	#getting data form models
	users = User.objects.all().order_by('username')
	
	#get average for every user
	for user in users:
		average = 0
		bets = user.bet_set.all().exclude(tour_number = tour_current.tour_number)
		if bets.count() > 0:
			for bet in bets:
				average += bet.correct_num
			average = average / (bets.count())
			results[user.username] = average

	#context data initialization into dictionary 'args'
	args['results'] = results

	return render_to_response('bet/best_betters.html',args,context_instance = RequestContext(request))

def more_info(request,betid):
	"""returns page with more information of particular bet"""
	#define variables
	args = {}
	results = []
	statuses = []

	#getting data form models
	bet = get_object_or_404(Bet, pk = betid)
	tour = get_object_or_404(Tour, tour_number = bet.tour_number)
	matches = Match.objects.filter(tour = tour)
	
	#checking if user wins or loose in particular match
	if bet.match1 == 1:
		if matches[0].goal_first >  matches[0].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[0].first_team + ' победит')
	elif bet.match1 == 2:
		if matches[0].goal_first <  matches[0].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[0].second_team + ' победит')
	else:
		if matches[0].goal_first ==  matches[0].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match2 == 1:
		if matches[1].goal_first >  matches[1].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[1].first_team + ' победит')
	elif bet.match2 == 2:
		if matches[1].goal_first <  matches[1].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[1].second_team + ' победит')
	else:
		if matches[1].goal_first ==  matches[1].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match3 == 1:
		if matches[2].goal_first >  matches[2].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[2].first_team + ' победит')
	elif bet.match3 == 2:
		if matches[2].goal_first <  matches[2].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[2].second_team + ' победит')
	else:
		if matches[2].goal_first ==  matches[2].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match4 == 1:
		if matches[3].goal_first >  matches[3].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[3].first_team + ' победит')
	elif bet.match4 == 2:
		if matches[3].goal_first <  matches[3].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[3].second_team + ' победит')
	else:
		if matches[3].goal_first ==  matches[3].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match5 == 1:
		if matches[4].goal_first >  matches[4].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[4].first_team + ' победит')
	elif bet.match5 == 2:
		if matches[4].goal_first <  matches[4].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[4].second_team + ' победит')
	else:
		if matches[4].goal_first ==  matches[4].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match6 == 1:
		if matches[5].goal_first >  matches[5].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[5].first_team + ' победит')
	elif bet.match6 == 2:
		if matches[5].goal_first <  matches[5].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[5].second_team + ' победит')
	else:
		if matches[5].goal_first ==  matches[5].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match7 == 1:
		if matches[6].goal_first >  matches[6].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[6].first_team + ' победит')
	elif bet.match7 == 2:
		if matches[6].goal_first <  matches[6].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[6].second_team + ' победит')
	else:
		if matches[6].goal_first ==  matches[6].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match8 == 1:
		if matches[7].goal_first >  matches[7].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[7].first_team + ' победит')
	elif bet.match8 == 2:
		if matches[7].goal_first <  matches[7].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[7].second_team + ' победит')
	else:
		if matches[7].goal_first ==  matches[7].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match9 == 1:
		if matches[8].goal_first >  matches[8].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[8].first_team + ' победит')
	elif bet.match9 == 2:
		if matches[8].goal_first <  matches[8].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[8].second_team + ' победит')
	else:
		if matches[8].goal_first ==  matches[8].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')
	if bet.match10 == 1:
		if matches[9].goal_first >  matches[9].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[9].first_team + ' победит')
	elif bet.match10 == 2:
		if matches[9].goal_first <  matches[9].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append(matches[9].second_team + ' победит')
	else:
		if matches[9].goal_first ==  matches[9].goal_second:
			statuses.append(1)
		else:
			statuses.append(0)
		results.append('ничья')

	#context data initialization into dictionary 'args'
	args['statuses'] = statuses
	args['results'] = results
	args['bet'] = bet
	args['matches'] = matches
	return render_to_response('bet/more_info.html',args,context_instance = RequestContext(request))

@login_required(login_url=reverse_lazy('main:signin'))
def check(request,tourid):
	"""this view does something """

	if request.user == User.objects.get(username = 'ariet'):
		#getting data form models
	    bets = Bet.objects.filter(tour_number = tourid)
	    matches = Match.objects.filter(tour = tourid)

	    #check if user made a true or wrong guess
	    for bet in range(0,len(bets)):
	        counter = 0 
	        if matches[0].goal_first >  matches[0].goal_second:
	        	if bets[bet].match1 == 1:
	        		counter += 1
	        elif matches[0].goal_first <  matches[0].goal_second:
	        	if bets[bet].match1 == 2:
	        		counter += 1
	        else:
	        	if bets[bet].match1 == 3:
	        		counter += 1

	        if matches[1].goal_first >  matches[1].goal_second:
	        	if bets[bet].match2 == 1:
	        		counter += 1
	        elif matches[1].goal_first <  matches[1].goal_second:
	        	if bets[bet].match2 == 2:

bet/templates/bet/archive.html
{% load staticfiles %}
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>221.kg</title>

    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css'%}">
    
  </head>

  <body>
  <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVJK9M"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MVJK9M');</script>
  <!-- End Google Tag Manager -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" href="{% url 'bet:index'%}"> <img id="logo" src="{% static 'images/logo1.png'%}"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'bet:make_bet'%}">Сделать ставку</a></li>
            <li class="active"><a href="{% url 'bet:archive' %}">Резултаты</a></li>
            <li><a href="{% url 'bet:how_it_works'%}">Как это работает</a></li>
            <li><a href="{% url 'bet:team'%}">О нас</a></li>
            <li><a href="#footer">Kонтакты</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'main:profile' %}">{{user.username}}</a></li>
            <li>
            <a><span data-toggle="modal" data-target="#signout"><span style="cursor:pointer">выйти</span></span></a>
            </li>
            {% else %}
            <li><a href="{% url 'main:signin' 'bet'%}">Войти</a></li>
            <li><a href="{% url 'main:signup' %}">Регистрация</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Here we have maincontent -->
    <br><br>
    <div class="maincontent">
<div style="background-color:#ECE9E9;border-radius:100px;" class="container">
    	<div style="padding:20px;" class="row">
    		<div class="col-md-4 col-md-offset-4">
    			
    			<br><br><br><br>
          <a href="{% url 'bet:best_betters'%}"><div class="alert alert-info text-center" role="alert">Рейтинг пользователей</div></a>
          
          <br><br><br><br><br>

         <div class="alert alert-success text-center" role="alert">Выбери номер тура</div>
                <table class="table table-hover">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>#-й Тур </th>
                        </tr>
                      </thead>
                      <tbody>
                       {% for tour in tours %}
                        
                        <tr>
                          <td>
                          <a href="{% url 'bet:tour_result' tour.tour_number%}" style="display:block;color:green;
    text-decoration:none;"><strong>{{tour.tour_number}}-й Тур</strong></a> </td>
                        </tr>
                       {% endfor%}
                      </tbody>
                    </table>
                </table>
                <br><br><br><br><br><br><br><br><br><br><br><br>
    		</div>
    	</div>
    </div>

    </div>
    <br><br>
    <div class="footer">
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span>Подпишись на наш Twitter<br>
            </a>

            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
              </span>Cтраничка Facebook <br>
            </a>  
          </div>

          <div class="col-md-6">
            <span class="fa-stack fa-lg text-left">
               <i class="fa fa-square-o fa-stack-2x"></i>
               <i class="fa fa-phone fa-stack-1x"></i>
            </span> +996556606737<br>
            <span class="fa-stack fa-lg text-left">
              <i class="fa fa-square-o fa-stack-2x"></i>
              <i class="fa fa-map-marker fa-stack-1x"></i>
            </span>Тунгуч,улица Анкара 1/8<br>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- Core JavaScript Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> 
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>

<!-- Exit  model page -->
    <div class="modal fade" id="signout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{user.first_name}} {{user.last_name}}</h4>
            </div>
            <div class="modal-body">
                <h4>вы уверены что хотите выйти?</h4>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <a href="{% url 'main:signout'%}"><button type="button" class="btn btn-primary">Выйти</button></a>
                </div>
            </div>
        </div>
      </div>
    </div>


<!-- WWW.NET.KG , code for http://221.kg -->
<script language="javascript" type="text/javascript">
 java="1.0";
 java1=""+"refer="+escape(document.referrer)+"&amp;page="+escape(window.location.href);
 document.cookie="astratop=1; path=/";
 java1+="&amp;c="+(document.cookie?"yes":"now");
</script>
<script language="javascript1.1" type="text/javascript">
 java="1.1";
 java1+="&amp;java="+(navigator.javaEnabled()?"yes":"now");
</script>
<script language="javascript1.2" type="text/javascript">
 java="1.2";
 java1+="&amp;razresh="+screen.width+'x'+screen.height+"&amp;cvet="+
 (((navigator.appName.substring(0,3)=="Mic"))?
 screen.colorDepth:screen.pixelDepth);
</script>
<script language="javascript1.3" type="text/javascript">java="1.3"</script>
<script language="javascript" type="text/javascript">
 java1+="&amp;jscript="+java+"&amp;rand="+Math.random();
 document.write("<a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'>"+
 "<img src='http://www.net.kg/img.php?id=4236&amp;"+java1+
 "' border='0' alt='WWW.NET.KG' width='88' height='10' /></a>");
</script>
<noscript>
 <a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'><img
  src="http://www.net.kg/img.php?id=4236" border='0' alt='WWW.NET.KG' width='88'
  height='10' /></a>
</noscript>
<!-- /WWW.NET.KG -->

 </body>
</html>
    
    