bet/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'bet.views.index', name='index'),
    url(r'^make_bet$', 'bet.views.make_bet', name='make_bet'),
    url(r'^archive$', 'bet.views.archive', name='archive'),
    url(r'^best_betters$', 'bet.views.best_betters', name='best_betters'),
    url(r'^tour_result/more_info/(?P<betid>\d+)$', 'bet.views.more_info', name='more_info'),
    url(r'^tour_result/(?P<tourid>\d+)$', 'bet.views.tour_result', name='tour_result'),
    url(r'^check/(?P<tourid>\d+)$', 'bet.views.check', name='check'),
    url(r'^team$', 'bet.views.team', name='team'),
    url(r'^how_it_works$', 'bet.views.how_it_works', name='how_it_works'),

)

main/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kgzone.views.home', name='home'),    reset_password_complate
    # url(r'^blog/', include('blog.urls')),     

    url(r'^$', 'main.views.main', name='main'),
    url(r'^signin/(?P<key>.+)$', 'main.views.signin', name='signin'),
    url(r'^signin$', 'main.views.signin', name='signin'),
    url(r'^signup$', 'main.views.signup', name='signup'),
    url(r'^signout$', 'main.views.signout', name='signout'),
    url(r'^team$', 'main.views.team', name='team'),
    url(r'^profile/modify_profile/$', 'main.views.modify_profile', name='modify_profile'),
    url(r'^profile/change_password/$', 'main.views.change_password', name='change_password'),
    url(r'^profile/$', 'main.views.profile', name='profile'),
)

www221kg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'www221kg.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^special/', include(admin.site.urls)),
    url(r'^reservation/',include('reservation.urls',namespace='reservation')),
    url(r'^news/',include('news.urls',namespace='news')),
    url(r'^bet/',include('bet.urls', namespace='bet')),
    url(r'^pro/',include('pro_owner.urls', namespace='pro_owner')),
	url(r'^',include('main.urls',namespace='main')),
    url(r'^',include('password_reset.urls')),
    
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)
urlpatterns += patterns('',
   (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.MEDIA_ROOT}))

main/models.py
#import python packeges and files
from datetime import datetime
#import django packeges and files
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Information(models.Model):
	"""This is class which stores all information about particular user"""

	user = models.OneToOneField(User,primary_key=True, verbose_name='ползователь')
	phone_number = models.IntegerField('номер телефона')
	can_book = models.BooleanField('может бронировать', default=False)

	def __unicode__(self):
		return self.user.first_name +" "+ self.user.last_name

	class Meta:
		verbose_name = "инфо ползователья"
		verbose_name_plural = "инфо ползовательей"

main/views.py
#import of django
from django.shortcuts import render_to_response, redirect
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse , reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
#impoer of models 
from .models import Information
from django.contrib.auth.models import User


# Create your views here.

def main(request):
	
	return render_to_response('main/main.html',{})

def team(request):
	args={}
	
	if request.user.is_authenticated():
		args["user"] = request.user
	return render_to_response('main/team.html',args)

def signin(request,key = 'main'):
	if request.user.is_authenticated():
		return redirect(reverse("main:main"))
	args={}
	args.update(csrf(request))

	if request.POST:
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				args['user'] = user
				if key == 'bet':
					return redirect(reverse('bet:index'))
				if key == 'reservation':
					return redirect(reverse('reservation:index'))
				if key == 'main':
					return redirect(reverse('main:main'))
			else:
				args['error_message'] = "Ваш аккаунт временно заблокирован"
				return render_to_response('main/signin.html',args)
		else:
			args['error_message'] = "Имя пользователя и пароль не совпадают, попробуйте еще раз. "
			return render_to_response('main/signin.html',args)

	else:
		return render_to_response('main/signin.html',args)

def signup(request):
	if request.user.is_authenticated():
		return redirect(reverse("main:main"))

	args={}
	args.update(csrf(request))
	validation = True
	all_users = User.objects.all()
	if request.POST:
		first_name = request.POST.get('first_name','')
		last_name = request.POST.get('last_name','')
		phone_num = request.POST.get('phone_num','')
		username = request.POST.get('username','')
		email = request.POST.get('e_mail','')
		password1 = request.POST.get('password1','')
		password2 = request.POST.get('password2','')

		#field validation:
		#first_name validation
		if len(first_name) < 2 :
			args['first_name_error'] = 'Слишком короткое имя'
			validation = False
		else:
			args['first_name'] = first_name
		if len(last_name) < 2 :
		#last_name validation
			args['last_name_error'] = 'Слишком короткая фамилия'
			validation = False
		else:
			args['last_name'] = last_name
		#phone_number validation
		if len(phone_num) != 10:
			validation = False
			args['phone_num_error'] = "Пожайлуста введите номер телефона в правилном 10 значном формате например : (0555123456)"
		else:
			phone_valid = True
			for i in phone_num:
				if ord(i) > 57 or ord(i) < 48:
					phone_valid = False
					break
			if phone_valid :
				if_number_in_use = Information.objects.filter(phone_number=phone_num[1:])
				if if_number_in_use.count() > 0: 
					args['phone_num_error'] = "Этот номер уже используется"
				else:
					args['phone_num'] = phone_num
			else:
				validation = False
				args['phone_num_error'] = "Пожайлуста введите номер телефона правилно например : (0555123456)"
		#username validation
		if len(username) > 2:
			users_using_thisname = all_users.filter(username__iexact=username)
			if users_using_thisname.count() > 0:
				validation = False
				args['username_error'] = 'Этот логин уже используется'
			else:
				args['username'] = username
		else:
			args['username_error'] = 'Слишком короткий логин'

		#password validation
		if len(password1) < 6 or len(password2) < 6:
			validation = False
			args['password_error'] = 'Пароль должен состоять из 6 и более символов'

		#email validation
		users_using_email = all_users.filter(email=email)
		if users_using_email.count() > 0:
			validation = False
			args['email_error'] = 'Этот email уже зарегистрирован' 
		else:
			args['email'] = email

		if validation == False:
			return render_to_response('main/signup.html', args)

		if password1 == password2:
			user = User.objects.create_user(username = username, email = email, password = password1)
			user.first_name = first_name
			user.last_name = last_name
			user.save()
			information = Information.objects.create(user = user, phone_number = phone_num,can_book = False)
			information.save()
			return redirect(reverse('main:signin'))
		else:
			args['email'] = email
			args['password_error'] = 'Пароли не совпадают'
			return render_to_response('main/signup.html', args)

	else:
		return render_to_response('main/signup.html',args)

def signout(request):
	logout(request)
	return redirect(reverse('main:main'))

@login_required(login_url=reverse_lazy('main:signin'))
def profile(request):
	args = {}
	user = request.user
	args['user'] = user
	return render_to_response('main/profile.html',args)

@login_required(login_url=reverse_lazy('main:signin'))
def modify_profile(request):
	args = {}
	args.update(csrf(request))
	validation = True
	user = request.user

	if request.POST:
		first_name = request.POST.get('firstname','')
		last_name = request.POST.get('lastname','')
		email = request.POST.get('email','')

		#field validation:
		#first_name validation
		if len(first_name) < 2 :
			args['first_name_error'] = 'Слишком короткое имя'
			validation = False

		if len(last_name) < 2 :
		#last_name validation
			args['last_name_error'] = 'Слишком короткая фамилия'
			validation = False

		users_using_email = User.objects.all().filter(email=email)
		if users_using_email.count() > 0:
			args['email_error'] = 'Этот email уже зарегистрирован'
			validation = False

		if validation == False:
			args['user'] = user
			return render_to_response('main/modify_profile.html', args)

		user.email = email
		user.first_name = first_name
		user.last_name = last_name
		user.save()
		return redirect(reverse('main:profile'))
	else:
		args['user'] = user
		return render_to_response('main/modify_profile.html',args)

@login_required(login_url=reverse_lazy('main:signin'))
def change_password(request):
	args = {}
	args.update(csrf(request))
	user = request.user
	args['user'] = user
	if request.POST:
		password1 = request.POST.get('password1','')
		password2 = request.POST.get('password2','')

		if len(password1) < 6 or len(password2) < 6:
			args['password_error'] = 'Пароль должен состоять из 6 и более символов'
			return render_to_response('main/change_password.html',args)
		if password1 == password2:
			user.set_password(password1)
			user.save()
			args['success_message'] = 'Ваш пароль успешно изменен'
		else:
			args['password_error'] = 'Пароли не совпадают'
		return render_to_response('main/change_password.html',args)
	else:
		return render_to_response('main/change_password.html',args)

main/templates/main/change_password.html
{% load staticfiles %}
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>221.kg</title>

    <!-- here is the font which we have got from google -->
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/demo.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css'%}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    



    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
    
    <!-- here we have font-awsome link -->
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css'%}">
    <link href="{% static 'css/signup.css' %}" rel="stylesheet">
  </head>

  <body>
  <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVJK9M"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MVJK9M');</script>
  <!-- End Google Tag Manager -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" href="{% url 'main:main' %}"> <img id="logo" src="{% static 'images/logo1.png'%}"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'main:team'%}">О нас</a></li>
            <li><a href="#footer">Kонтакты</a></li>
            <li class="active"><a href="{%url 'main:profile'%}">{{user.username}}</a></li>
            <li><a href="{% url 'main:signout'%}">выйти</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Here we have maincontent -->
    <div class="maincontent">
    <div class="container">

    <br><br><br>
    {% if success_message%}
    <br>
    <div class="alert alert-success" role="alert">{{success_message}}</div>
    <br>
    {% endif %}
    
      <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{user.first_name}} {{user.last_name}}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-2 col-lg-2 " align="center">  </div>
                <div class=" col-md-8 col-lg-8 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>логин:</td>
                        <td>{{user.username}}</td>
                      </tr>
                      <tr>
                        <td>номер телефона:</td>
                        <td>0{{user.information.phone_number}}</td>
                      </tr>                
                      <tr>
                        <td>email</td>
                        <td><a href="">{{user.email}}</a></td>
                      </tr>
                      <tr>
                        <td>статус активации</td>
                        <td>
                          {% if user.information.can_book%}
                          <span class"bg-success">аккаунт активирован</span>
                          {% else %}
                          <span class"bg-danger">аккаунт не активирован</span>
                          {% endif%}
                        </td>
                      </tr>
                     
                    </tbody>
                  </table>
                  
                 
                </div>
                <div class="col-md-2 col-lg-2 " align="center">  </div>
              </div>
            </div>
            
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
        <form action="" method="POST" role="form">
                    {% csrf_token %}
                        {% if password_error %}
                          <div class="alert alert-danger" role="alert">{{password_error}}</div>
                        {% endif %}
                        <div class="form-group">
                            <label for="password1">Пароль</label>
                            <input type="password" class="form-control" name="password1" id="password1" required>
                        </div>
                                           
                        <div class="form-group">
                            <label for="password2">Повторный пароль</label>
                            <input type="password" class="form-control" name="password2" id="password2"  required>
                        </div>
                        <div class="span7 text-center">
                        <br>
                            <input type='submit' value='Сменить пароль' class="btn btn-primary btn-lg btn-block" role="button">
                            <br>
                            <a href="{% url 'main:profile'%}"><button type="button" class="btn btn-default btn-lg btn-block">Отмена</button></a>
                        </div>
                    </form>
                    </div>
      </div>
      
      <br><br><br><br>
    </div>
    </div>
    
<div class="footer">
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span>Подпишись на наш Twitter<br>
            </a>

            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
              </span>Cтраничка Facebook <br>
            </a>  
          </div>

          <div class="col-md-6">
            <span class="fa-stack fa-lg text-left">
               <i class="fa fa-square-o fa-stack-2x"></i>
               <i class="fa fa-phone fa-stack-1x"></i>
            </span> +996556606737<br>
            <span class="fa-stack fa-lg text-left">
              <i class="fa fa-square-o fa-stack-2x"></i>
              <i class="fa fa-map-marker fa-stack-1x"></i>
            </span>Тунгуч,улица Анкара 1/8<br>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{% static 'js/jquery.easing.min.js'%}"></script> 
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/wow.min.js'%}"></script>
  <script src="{% static 'js/custom.js'%}"></script>



  <!-- WWW.NET.KG , code for http://221.kg -->
<script language="javascript" type="text/javascript">
 java="1.0";
 java1=""+"refer="+escape(document.referrer)+"&amp;page="+escape(window.location.href);
 document.cookie="astratop=1; path=/";
 java1+="&amp;c="+(document.cookie?"yes":"now");
</script>
<script language="javascript1.1" type="text/javascript">
 java="1.1";
 java1+="&amp;java="+(navigator.javaEnabled()?"yes":"now");
</script>
<script language="javascript1.2" type="text/javascript">
 java="1.2";
 java1+="&amp;razresh="+screen.width+'x'+screen.height+"&amp;cvet="+
 (((navigator.appName.substring(0,3)=="Mic"))?
 screen.colorDepth:screen.pixelDepth);
</script>
<script language="javascript1.3" type="text/javascript">java="1.3"</script>
<script language="javascript" type="text/javascript">
 java1+="&amp;jscript="+java+"&amp;rand="+Math.random();
 document.write("<a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'>"+
 "<img src='http://www.net.kg/img.php?id=4236&amp;"+java1+
 "' border='0' alt='WWW.NET.KG' width='88' height='10' /></a>");
</script>
<noscript>
 <a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'><img
  src="http://www.net.kg/img.php?id=4236" border='0' alt='WWW.NET.KG' width='88'
  height='10' /></a>
</noscript>
<!-- /WWW.NET.KG -->

 </body>
</html>

main/templates/main/profile.html
{% load staticfiles %}
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>221.kg</title>

    <!-- here is the font which we have got from google -->
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/demo.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css'%}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    



    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
    
    <!-- here we have font-awsome link -->
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css'%}">
    <link href="{% static 'css/signup.css' %}" rel="stylesheet">
  </head>

  <body>
  <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVJK9M"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MVJK9M');</script>
  <!-- End Google Tag Manager -->

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" href="{% url 'main:main' %}"> <img id="logo" src="{% static 'images/logo1.png'%}"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{%url 'main:team'%}">О нас</a></li>
            <li><a href="#footer">Kонтакты</a></li>
            <li class="active"><a href="">{{user.username}}</a></li>
            <li>
            <a><span data-toggle="modal" data-target="#signout"><span style="cursor:pointer">выйти</span></span></a>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Here we have maincontent -->
    <div class="maincontent">
    <div class="container">
    <br><br><br><br><br><br><br><br><br>
      <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{user.first_name}} {{user.last_name}}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-2 col-lg-2 " align="center">  </div>
                <div class=" col-md-8 col-lg-8 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>логин:</td>
                        <td>{{user.username}}</td>
                      </tr>
                      <tr>
                        <td>номер телефона:</td>
                        <td>0{{user.information.phone_number}}</td>
                      </tr>                
                      <tr>
                        <td>email</td>
                        <td><a href="">{{user.email}}</a></td>
                      </tr>
                      <tr>
                        <td>статус активации</td>
                        <td>
                          {% if user.information.can_book%}
                          <span class"bg-success">аккаунт активирован</span>
                          {% else %}
                          <span class"bg-danger">аккаунт не активирован</span>
                          {% endif%}
                        </td>
                      </tr>
                     
                    </tbody>
                  </table>
                  
                  <p class="text-center"><a href="{%url 'main:modify_profile'%}">Редактировать аккаунт</a></p>
                  <p class="text-center"><a href="{%url 'main:change_password'%}">Сменить пароль</a></p>
                </div>
                <div class="col-md-2 col-lg-2 " align="center">  </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
      <br><br><br><br><br><br><br><br><br><br><br>
    </div>
    </div>
    
<div class="footer">
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </span>Подпишись на наш Twitter<br>
            </a>

            <a href="https://www.facebook.com/oskar.dasilva.7">
              <span class="fa-stack fa-lg text-left">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
              </span>Cтраничка Facebook <br>
            </a>  
          </div>

          <div class="col-md-6">
            <span class="fa-stack fa-lg text-left">
               <i class="fa fa-square-o fa-stack-2x"></i>
               <i class="fa fa-phone fa-stack-1x"></i>
            </span> +996556606737<br>
            <span class="fa-stack fa-lg text-left">
              <i class="fa fa-square-o fa-stack-2x"></i>
              <i class="fa fa-map-marker fa-stack-1x"></i>
            </span>Тунгуч,улица Анкара 1/8<br>
          </div>
        </div>
      </div>
    </footer>
  </div>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> 
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>


    <!-- Exit  model page -->
    <div class="modal fade" id="signout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{user.first_name}} {{user.last_name}}</h4>
            </div>
            <div class="modal-body">
                <h4>вы уверены что хотите выйти?</h4>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <a href="{% url 'main:signout'%}"><button type="button" class="btn btn-primary">Выйти</button></a>
                </div>
            </div>
        </div>
      </div>
    </div>


<!-- WWW.NET.KG , code for http://221.kg -->
<script language="javascript" type="text/javascript">
 java="1.0";
 java1=""+"refer="+escape(document.referrer)+"&amp;page="+escape(window.location.href);
 document.cookie="astratop=1; path=/";
 java1+="&amp;c="+(document.cookie?"yes":"now");
</script>
<script language="javascript1.1" type="text/javascript">
 java="1.1";
 java1+="&amp;java="+(navigator.javaEnabled()?"yes":"now");
</script>
<script language="javascript1.2" type="text/javascript">
 java="1.2";
 java1+="&amp;razresh="+screen.width+'x'+screen.height+"&amp;cvet="+
 (((navigator.appName.substring(0,3)=="Mic"))?
 screen.colorDepth:screen.pixelDepth);
</script>
<script language="javascript1.3" type="text/javascript">java="1.3"</script>
<script language="javascript" type="text/javascript">
 java1+="&amp;jscript="+java+"&amp;rand="+Math.random();
 document.write("<a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'>"+
 "<img src='http://www.net.kg/img.php?id=4236&amp;"+java1+
 "' border='0' alt='WWW.NET.KG' width='88' height='10' /></a>");
</script>
<noscript>
 <a href='http://www.net.kg/stat.php?id=4236&amp;fromsite=4236' target='_blank'><img
  src="http://www.net.kg/img.php?id=4236" border='0' alt='WWW.NET.KG' width='88'
  height='10' /></a>
</noscript>
<!-- /WWW.NET.KG -->
 
 </body>
</html>